### ISSUE TITLE
(wrong-number-of-arguments (4 . 4) 3)

### ISSUE THREAD

**Issue by manuel-uberti** [joostkremers/visual-fill-column#14] opened 2016-02-27 08:42 UTC
Hi,
I've just upgraded `visual-fill-column` from MELPA. With `visual-fill-column-mode` active, I get this error when doing `C-x 2`:
```
Debugger entered--Lisp error: (wrong-number-of-arguments (4 . 4) 3)
  visual-fill-column--split-window(#<window 3 on *Backtrace*> nil below)
  split-window(nil nil)
  split-window-below(nil)
  funcall-interactively(split-window-below nil)
  call-interactively(split-window-below nil nil)
  command-execute(split-window-below)
```
It happens when doing `M-x` as well.

**Comment by joostkremers** [comment] 2016-02-28 17:04
Sorry, didn't check the last commit properly. Should be fixed now.

**Comment by manuel-uberti** [comment] 2016-02-29 09:32
Perfect, it's working now. Thank you!

**Comment by joostkremers** [comment] 2016-02-29 10:22
I actually made another mistake, which should also be fixed now.

**Comment by jsy1001** [comment] 2016-03-10 11:00
I am getting a similar problem when doing `C-x 2` with version 1.7:

    visual-fill-column-split-window: Wrong number of arguments: #[(&optional window size side) "Æ!	

**Comment by joostkremers** [comment] 2016-03-10 13:01
Have you tried restarting Emacs after updating `visual-fill-column-mode`? Sometimes updating packages in a running Emacs doesn't work right.

If you did, though, I'd need to know what version of Emacs you're running.

**Comment by jsy1001** [comment] 2016-03-10 13:03
Yes, I've tried restarting.

I'm using GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.7)

**Comment by joostkremers** [comment] 2016-03-10 15:53
> I'm using GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.7)

Well, in that case, since the fix that causes your problem was added to handle changes introduced in the (not yet released) Emacs 25, the best remedy is probably to make that fix dependent on the Emacs version.

I've done this now, should be on Melpa in a few hours. Let me know if you run into further problems.

**Comment by jsy1001** [comment] 2016-03-11 09:30
It works fine now - thank you for the quick response.

**Comment by joostkremers** [comment] 2016-03-11 09:54
I'm glad it works now. I found out the cause of the problem just now: in Emacs 24.3, `split-window` takes only three (optional) arguments, starting from Emacs 24.4, it takes four.

Thanks for reporting this.

**Closed by joostkremers** 2016-03-11 09:54 UTC
