### ISSUE TITLE
text scaling breaks visual-fill-columns

### ISSUE THREAD

**Issue by molok** [joostkremers/visual-fill-column#54] opened 2021-11-04 14:02 UTC
after issuing `text-scale-decrease`, widening the window reduces the text width

example with default text scaling, working correctly
![image](https://user-images.githubusercontent.com/34475/140928537-04f63308-eab5-4747-9d8d-ab3624df752e.png)
after resizing the window the characters per line don't change, as expected
![image](https://user-images.githubusercontent.com/34475/140928551-f9d5f049-ef49-4db5-a962-0ef0559835df.png)

example after issuing `text-scale-decrease`
![image](https://user-images.githubusercontent.com/34475/140928577-9ed4712e-7259-49a6-81e2-a376222cf3d4.png)
after widening the window, the number of characters decreases unexpectedly
![image](https://user-images.githubusercontent.com/34475/140928600-bd9f3778-3845-424d-aaf7-cdebae55ce58.png)
the wider the window is, the narrower the line gets
issuing `redraw-display` doesn't change the behavior.

GNU Emacs 27.2.50 + Doom Emacs

**Comment by joostkremers** [comment] 2021-11-08 22:53
There's a comment in the README [here](https://github.com/joostkremers/visual-fill-column#adjusting-text-size) that could be relevant. If not, could you elaborate a bit? (And feel free to include any images directly on Github.)

**Comment by molok** [comment] 2021-11-09 13:10
@joostkremers I have updated the issue, I hope the problem is more clear now.

**Comment by joostkremers** [comment] 2021-11-12 21:16
> @joostkremers I have updated the issue, I hope the problem is more clear now.

Thanks, I see now what you mean. I get the same effect. Not sure what's going on, though. When the text size is decreased, the width of the right margin is adjusted to account for the smaller font size. That is, the margin width (expressed as the number of columns) is larger, but because of the smaller font size, this should not result in visually wider margins.

It seems that the margin width is no longer affected by the font size used in the buffer, because if I remove the code that adjusts the number of margin columns for the text scale factor, the margins stays the same.

Either that or the effect you describe was actually intended by the person who added that code (it wasn't added by me).

I'll investigate a bit and then decide what to do.

**Comment by abolognino** [comment] 2021-11-15 11:39
@joostkremers I'm probably missing something, but I don't get why scaling is considered at all. My understanding is that visual-line-mode should soft-wrap lines at a user-defined column, just like auto-fill mode, but using soft-wrapping instead of hard-wrapping.
auto-fill mode doesn't care about text scaling at all.

**Comment by molok** [comment] 2021-11-15 11:40
@joostkremers I'm probably missing something, but I don't get why scaling is considered at all. My understanding is that visual-line-mode should soft-wrap lines at a user-defined column, just like auto-fill mode, but using soft-wrapping instead of hard-wrapping.
auto-fill mode doesn't care about text scaling at all

**Comment by joostkremers** [comment] 2021-11-16 07:52
> @joostkremers I'm probably missing something, but I don't get why scaling is considered at all.

That behaviour was added in response to issue #12. At the time, everybody was happy and there haven't been any bug reports about it until now. I don't know if something changed recently in the way that Emacs computes the margins, or if the effect is simply too strong in some cases.

@cpitclaudel If you see this, would you mind taking a look at this issue and tell us what you think?

The simplest solution would probably be to make this behaviour configurable.

**Comment by cpitclaudel** [comment] 2021-11-16 15:54
> @cpitclaudel If you see this, would you mind taking a look at this issue and tell us what you think?

I'm not sure I'm 100% following, unfortunately (I don't understand @molok's comment "but I don't get why scaling is considered at all.")

**Comment by molok** [comment] 2021-11-16 15:59
@cpitclaudel if the purpose of this emacs mode is to soft-wrap lines after `visual-fill-column-width` characters, why would text scaling affect the behaviour?

**Comment by cpitclaudel** [comment] 2021-11-16 19:27
Because the width that `visual-fill-column-width` characters takes depends on how wide the characters are?

**Comment by molok** [comment] 2021-11-16 22:35
@cpitclaudel @joostkremers ok, anyhow, as documented in this issue there seems to be a bug linked to text scaling.
I'll open a feature request to optionally disable the logic about text scaling because it doesn't fit my (and possibly others) workflow, I just need soft-wrapping after n-characters, regardless of the text-scale

**Comment by joostkremers** [comment] 2021-11-16 23:38
> Because the width that `visual-fill-column-width` characters takes depends on how wide the characters are?

The problem is that `visual-fill-column` cannot set the column to wrap at. What it needs to do is set the left margin to a value that ensures the text area has the requested width. So if the font size is decreased, the margin needs to be increased in order to make sure the text is still wrapped at the same column.

If the scaling is taken out, decreasing the text size doesn't change the width of the margin, so as a result the text is actually wrapped at a higher column.

I do think it is worth making this a user-configurable option, so I'll see about doing that ASAP.

**Comment by cpitclaudel** [comment] 2021-11-17 00:36
> I just need soft-wrapping after n-characters, regardless of the text-scale

Yep, that's precisely what I was trying to get at.  I hope @joostkremers 's explanation is clearer than mine regarding why this requires test-scaling to affect the behavior

**Comment by molok** [comment] 2021-11-17 08:17
@joostkremers @cpitclaudel OK, I get it now, thanks for the explanation.

**Comment by joostkremers** [comment] 2021-11-17 23:46
> > I just need soft-wrapping after n-characters, regardless of the text-scale
> 
> Yep, that's precisely what I was trying to get at. I hope @joostkremers 's explanation is clearer than mine regarding why this requires test-scaling to affect the behavior

Still, there does seem to be a problem. The purpose of calculating in the text scaling factor was to ensure that the text remains wrapped at the same column, i.e., decreasing the font size shouldn't change the wrapping. However, when I press `C-x C--` once, the text gets rewrapped and becomes too narrow. So something is going wrong...

**Comment by joostkremers** [comment] 2021-11-18 00:55
I have pushed a commit that adds an option to disable the text-scaling adjustment of the margins. This is not really a solution for the bug that I believe exists, but it's somewhat of a workaround.

Note that I'm about to archive this Github repo, I've moved the code to codeberg.org here: https://codeberg.org/joostkremers/visual-fill-column. The Melpa recipe has already been updated, so if you've installed `visual-fill-column` through Melpa, the update should appear automatically. If you're using some other method, you may need to update the repo.

**Comment by joostkremers** [comment] 2021-11-18 01:05
I created an issue on codeberg: https://codeberg.org/joostkremers/visual-fill-column/issues/1 and I'm closing this issue here.

**Closed by joostkremers** 2021-11-18 01:05 UTC
Labels: enhancement
