### ISSUE TITLE
Fcitx input method outside the margin 

### ISSUE THREAD

**Issue by HomelandScenery** [joostkremers/visual-fill-column#25] opened 2017-02-20 02:27 UTC
Hello ,thanks for this great package , I use it every day for my writing.

But now I have a problem, While using Fcitx input method to input Chinese in Ubuntu 16.04,the input method box is not in a correct location , the box is not in the page but outside the margin . And to disable visual-fill-column-mode, the input box is correct again.

However I use the same Emacs init file in Windows 7, the input box is correct whether visual-fill-column-mode is on or off.

Please help,Thanks!

![vl1](https://cloud.githubusercontent.com/assets/19407813/23109599/7e5a4c82-f755-11e6-9747-aace5d48948f.png)
![vl2](https://cloud.githubusercontent.com/assets/19407813/23109600/7f34fd96-f755-11e6-8227-60da6b3cceb7.png)

emacs-version:
GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, GTK+ Version 2.24.30) of 2016-11-23
Spacemacs 0.200.5 ,Ubuntu 16.04

**Comment by joostkremers** [comment] 2017-02-20 12:16
I have no experience with Chinese input methods, but I assume that the thin blue line is your cursor and that the input box should follow it?

I suspect, though, that this is not an issue that `visual-fill-column-mode` has any control over. All `visual-fill-column-mode` really does is to widen the margin of a window, so that the text area is narrowed. So this would seem to be a bug either with Emacs, because it reports an incorrect cursor position, or in Fcitx, because it interprets the cursor position incorrectly.

I noticed that there is a FAQ on the Fcitx website that seems relevant:

https://fcitx-im.org/wiki/FAQ#Cursor_Following_problem

Which suggests that it is probably an Emacs bug. So you should probably file a bug report with Emacs, or if you prefer, I can do it.

**Comment by terlar** [comment] 2017-02-20 22:14
I can confirm that this same bug occurs with ibus also, so most likely a bug in Emacs and not something Fcitx specific.

**Comment by HomelandScenery** [comment] 2017-02-21 09:50
Thanks to the author's reply and friends' tests.
If you can confirm that it is Emacs Bug, it is a good idea to submit a report by you. Because I am only an ordinary user, and not familiar with emacs-lisp program , and my ability to express English is too bad :-)

**Comment by joostkremers** [comment] 2017-02-22 09:29
@terlar Thanks for the confirmation.

Could either you or @HomelandScenery try with `emacs -Q` and see if the problem persists (I suspect it does), and if yes, provide a screen shot? The procedure for this would be:

- start Emacs with `emacs -Q -L /path/to/visual-fill-column-<version>`

- Do `M-x ielm` (This step is not necessary, but convenient.)

- At the `ELISP>` prompt type: `(require 'visual-fill-column)`.

- Type `(setq-default visual-fill-column-center-text t)`.

- Open some text file and do `M-x visual-fill-column-mode`.

- Then open your input method in such a way that the problem is visible and take a screen shot.

Such a screen shot would be helpful in convincing the Emacs devs that there is a problem to be fixed, and the `emacs -Q` recipe is necessary to make sure it's not a problem with some local configuration.

Thanks!

**Comment by terlar** [comment] 2017-02-22 18:33
Here is a screenshot with the issue reproduced for ibus:

![2017-02-22-192749_2560x1600_scrot](https://cloud.githubusercontent.com/assets/280235/23226383/a1114186-f935-11e6-8054-f9b6860b5292.png)

Thank you for the steps, handy to get this done.

**Comment by joostkremers** [comment] 2017-02-22 23:03
Thanks! I'll post to emacs-devel when I have some time tomorrow.

**Comment by HomelandScenery** [comment] 2017-02-22 23:53
Here is a screenshot with the issue using fcitx:

![vl01](https://cloud.githubusercontent.com/assets/19407813/23238445/f58aa146-f99c-11e6-9d67-23c472a9b774.png)

![vl02](https://cloud.githubusercontent.com/assets/19407813/23238469/0e216fb4-f99d-11e6-96ed-0f8e3126ed2e.png)

Thank you @joostkremers

**Comment by joostkremers** [comment] 2017-02-28 14:02
Ok, I posted to `emacs-devel` with the problem, I'll let you know as soon as I learn more.

**Comment by HomelandScenery** [comment] 2017-04-24 08:48
Version 25.2 of the Emacs text editor is now available.
Can you tell me how to update Emacs in Ubuntu?
Here is how I intall Emacs .
```shell
tar -zxvf emacs-VERSION.tar.gz
cd emacs-VERSION
./configure # configure Emacs for your particular system
make # use Makefile to build components, then Emacs
make install
```

**Comment by joostkremers** [comment] 2018-02-08 20:18
Hi, I haven't followed up on this issue for a while, sorry about that. I was wondering if the issue still exists, or if it has been resolved in the mean time. If it's still a problem, I will investigate.

**Comment by merrickluo** [comment] 2018-07-22 05:02
Yes, I can confirm this still exists 
![image](https://user-images.githubusercontent.com/1495875/43042399-578c0054-8daf-11e8-9189-c1e29fc1fa4f.png)

My Emacs version is 26.1 `GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-05` and this is with fcitx.

**Comment by amosbird** [comment] 2021-03-24 15:30
Still facing this issue. It happens when there is a left margin, not specifically related to `visual-fill-column`

**Comment by amosbird** [comment] 2021-03-24 15:37
Heh, it's trivial to fix. We just need to adjust `xic_set_preeditarea` from setting `spot.x = WINDOW_TO_FRAME_PIXEL_X (w, x) + WINDOW_LEFT_FRINGE_WIDTH (w)` to `spot.x = WINDOW_TO_FRAME_PIXEL_X (w, x) + WINDOW_LEFT_FRINGE_WIDTH (w) + WINDOW_LEFT_MARGIN_WIDTH(w)`

**Comment by joostkremers** [comment] 2021-03-24 21:53
> Heh, it's trivial to fix. We just need to adjust `xic_set_preeditarea` from setting `spot.x = WINDOW_TO_FRAME_PIXEL_X (w, x) + WINDOW_LEFT_FRINGE_WIDTH (w)` to `spot.x = WINDOW_TO_FRAME_PIXEL_X (w, x) + WINDOW_LEFT_FRINGE_WIDTH (w) + WINDOW_LEFT_MARGIN_WIDTH(w)`

This should be changed in Emacs, right? I could  suggest this on the emacs-devel mailing list, but perhaps it'd be better if you do so? You'll be better able to explain the why and the how.

> Perhaps we should use fringe instead of margin in GUI emacs.

You mean in `visual-fill-column-mode`?

**Comment by amosbird** [comment] 2021-03-25 03:29
> You mean in `visual-fill-column-mode`?

Yes.

**Comment by joostkremers** [comment] 2021-03-25 05:31
> > You mean in `visual-fill-column-mode`?
> 
> Yes.

I considered that option back when I started `visual-fill-column-mode`, but decided against it, because the width of the fringes is always given in pixels, not in columns, and because it wouldn't work on the command line. I'd be willing to consider a PR, but I don't have time to work on it myself at the moment.

**Comment by amosbird** [comment] 2021-03-25 05:33
Ok. Lemme send a patch to emacs-devel.

**Comment by joostkremers** [comment] 2021-03-25 05:37
> Ok. Lemme send a patch to emacs-devel.

Great, thanks!

**Comment by amosbird** [comment] 2021-03-25 15:36
Patch accepted. We can close this now.

**Comment by joostkremers** [comment] 2021-03-25 15:44
Thanks!

**Closed by joostkremers** 2021-03-25 15:44 UTC
